wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714632703.0
    t:
      1:
      - 1
      - 9
      - 41
      - 51
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 51
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.11.8
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Validation/Input image._type
      5: 1
      6:
      - 1
    - 1: Validation/Input image.sha256
      5: 1
      6:
      - 1
    - 1: Validation/Input image.size
      5: 1
      6:
      - 1
    - 1: Validation/Input image.path
      5: 1
      6:
      - 1
    - 1: Validation/Input image.format
      5: 1
      6:
      - 1
    - 1: Validation/Input image.width
      5: 1
      6:
      - 1
    - 1: Validation/Input image.height
      5: 1
      6:
      - 1
    - 1: Validation/Output image._type
      5: 1
      6:
      - 1
    - 1: Validation/Output image.sha256
      5: 1
      6:
      - 1
    - 1: Validation/Output image.size
      5: 1
      6:
      - 1
    - 1: Validation/Output image.path
      5: 1
      6:
      - 1
    - 1: Validation/Output image.format
      5: 1
      6:
      - 1
    - 1: Validation/Output image.width
      5: 1
      6:
      - 1
    - 1: Validation/Output image.height
      5: 1
      6:
      - 1
    - 1: Validation/Annotation._type
      5: 1
      6:
      - 1
    - 1: Validation/Annotation.sha256
      5: 1
      6:
      - 1
    - 1: Validation/Annotation.size
      5: 1
      6:
      - 1
    - 1: Validation/Annotation.path
      5: 1
      6:
      - 1
    - 1: Validation/Annotation.format
      5: 1
      6:
      - 1
    - 1: Validation/Annotation.width
      5: 1
      6:
      - 1
    - 1: Validation/Annotation.height
      5: 1
      6:
      - 1
    - 1: lr-SGD/pg1
      5: 1
      6:
      - 1
    - 1: lr-SGD/pg2
      5: 1
      6:
      - 1
    - 1: LossStats/GradientNorm
      5: 1
      6:
      - 1
    - 1: train:loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: validation:loss
      5: 1
      6:
      - 1
    - 1: Validation_epoch/loss
      5: 1
      6:
      - 1
    - 1: Validation/Precision
      5: 1
      6:
      - 1
    - 1: Validation/Recall
      5: 1
      6:
      - 1
    - 1: Validation/F1-Score
      5: 1
      6:
      - 1
    - 1: Validation/Acc
      5: 1
      6:
      - 1
    - 1: Validation/mIoU
      5: 1
      6:
      - 1
    - 1: Validation/ECE
      5: 1
      6:
      - 1
network:
  desc: null
  value: <semantic_segmentation.models.deterministic_network.DeterministicNetwork
    object at 0x7fc2ef13ae10>
cfg:
  desc: null
  value:
    experiment:
      id: VOC_Drop0dot3_R50
    data:
      name: voc12
      path_to_dataset: /home/ego_exo4d/VOCdevkit/VOC2012
      depth: 3
      batch_size: 16
      train_shuffle: true
      num_workers: 16
    train:
      n_gpus: 1
      max_epoch: 30
      lr: 0.0001
      weight_decay: 0.0005
      num_mc_aleatoric: 50
      patience: 500
      visualization_interval: 50
      transformations:
        random_scale:
          min_scale: 0.5
          max_scale: 2.0
        random_crop:
          value: 513
        random_flip:
          prob: 0.5
    val:
      transformations:
        resize:
          value: 513
        center_crop:
          value: 513
    test:
      transformations:
        resize: null
    model:
      type: deterministic
      name: deeplabv3
      num_classes: 21
      loss: xentropy
